package com.example.OrderService.DTOs;

import com.example.OrderService.Models.ProductQuantity;
import lombok.Data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Data
public class OrderDTO {
    private Map<String,Long> listOfAllProductIDs; // List of product IDs
    private Long totalAmount; // Total amount of the order
    private Long userId; // User ID associated with the order


    private  String Status;

    // Constructors, getters, setters, toString, equals, and hashCode are generated by Lombok
    public List<ProductQuantity> getAllProductsforproductvity() {
        // Convert listOfAllProductIDs to a list of ProductQuantity objects
        return listOfAllProductIDs.entrySet().stream()
                .map(entry -> new ProductQuantity(entry.getKey(), entry.getValue()))
                .collect(Collectors.toList());
    }

    // Method to add or update product quantity
    public void setProductQuantity(String productId, Long quantity) {
        if (listOfAllProductIDs == null) {
            listOfAllProductIDs = new HashMap<>();
        }
        listOfAllProductIDs.put(productId, quantity);
    }
}