spring.application.name=OrderService

spring.data.mongodb.uri=mongodb://localhost:27017/OrderDetailsService

# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true
# eureka.client.service-url.default-zone=http://localhost:8761/eureka

# Server Port
server.port=8081

# Allow Bean Definition Overriding
spring.main.allow-bean-definition-overriding=true

# Logging Level
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.mongodb.driver=DEBUG
